# hit the ball to gain points
# if the robot hits the target, it wins the game

[simulation]
	numrobot = 1
	numobject = 3
	map = "simple_square"
	actuators = ["MotionVW", "Keyboard"]
	sensors = ["Pose", "Infrared", "Proximity"]
	[[simulation.objects]]
		file = "target"
		name = "target"
		x = -5
		y = -6
		z = 0
		[simulation.objects.properties]
			Label = "GOAL"
			GOAL = true
	[[simulation.objects]]
		file = "ball"
		name = "BALL1"
		x = 1
		y = 1
		z = 1
		[simulation.objects.properties]
			Label = "BALL"
			Object = true
	[[simulation.objects]]
		file = "ball"
		name = "BALL2"
		x = 2
		y = 2
		z = 2
		[simulation.objects.properties]
			Label = "BALL"
			Object = true
	[[simulation.camera_position]]
		x_cam = -18.0
		y_cam = -6.7
		z_cam = 10.8
		p_cam = 1.09
		q_cam = 0
		r_cam = -1.14
	[[simulation.robot_position]]
		x = 7
		y = 7
		z = 0
		p = 0
		q = 0
		r = 3.14
	[simulation.time]
		totalTime = 30
		simulationStopMode = "stopWhenNoTime"
	[simulation.initScore]
		k = 0
		initialScore = 0
		stopFlag = false
	[[simulation.score]]
		obj = "BALL1"
		score = 10
		stop = false
	[[simulation.score]]
		obj = "BALL2"
		score = 10
		stop = false
	[[simulation.score]]
		obj = "Wall"
		score = -10
		stop = false
	[[simulation.score]]
		obj = "target"
		score = 100
		stop = true
